config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :image, presence: true
  
  has_attached_file :image, styles: { :medium => "640x" }
  
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.create(post_params)
    if @post.save
      flash[:success] = "Your post has been created."
      redirect_to @post
    else
      flash[:alert] = "Not so fast! You need an image to post here!"
      render :new
    end
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  private
    def post_params
      params.require(:post).permit(:caption, :image)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)
    {
        :success => 'alert-success',
        :error => 'alert-danger',
        :alert => 'alert-warning',
        :notice => 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>iGram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
    <% end %>
    <%= yield %>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-container">
        <div class="navbar-header">
          <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
            <span class="sr-only">Toggle Navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-brand">
            <%= link_to "igram", root_path %>
          </div>
        </div>
        <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to "New Post", new_post_path %>
            </li>
            <li>
              <%= link_to "Login", '#' %>
            </li>
            <li>
              <%= link_to "Register", '#' %>
            </li>
          </ul>
        </div>
      </div>
    </header>
  </body>
</html>

app/views/posts/index.html.erb
<div class="posts-wrapper row">
  <% @posts.each do |post| %>
    <div class="post">
      <div class="post-head">
        <div class="name">
          Ben Walker
        </div>
      </div>
      <div class="image center-block">
        <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
      </div>
      <p class="caption">
        <%= post.caption %>
      </p>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :image %>
  <%= f.input :caption %>
  <%= f.button :submit %>
<% end %>

app/views/posts/show.html.erb
<div class="posts-wrapper row">
  <div class="post">
    <div class="post-head">
      <div class="name">
        Ben Walker
      </div>
    </div>
    <div class="image center-block">
      <%= image_tag @post.image.url(:medium) %>
    </div>
    <p class="caption">
      <%= @post.caption %>
    </p>
    <div class="text-center">
      <%= link_to "Cancel", posts_path %>
    </div>
  </div>
</div>